import '@/app/_styles/globals.css';
import Header from './_components/header/Header';
import { Barlow_Condensed } from 'next/font/google';
import { Barlow} from 'next/font/google';
import {Bellefair} from 'next/font/google'



const barlowCon = Barlow_Condensed({ subsets: ['latin'], weight: ['400'] });
const barlow = Barlow({ subsets: ['latin'], weight: ['400'] });
const bellefair = Bellefair({ subsets: ['latin'], weight: ['400'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	console.log(children);
	return (
		<html lang='en'style={{
				'--font-barlow-con': barlowCon.style.fontFamily,
			  '--font-bellefair': bellefair.style.fontFamily,
				'--font-barlow': barlow.style.fontFamily
			}} className={`${barlowCon.className}`}>
			<body className='pt-10 md:pt-0 lg:pt-10 bg-black text-slate-50 flex flex-col items-center'>
				<div className='h-24 w-screen'>
					<Header />
				</div>

				<main className=' w-full py-14 '>{children}</main>
			</body>
		</html>
	);
}
